### ISSUE TITLE
Migration make task errors at go get goose

### ISSUE THREAD

**Issue by realisation** [vulcanize/ipfs-blockchain-watcher#6]
I'm getting an error on the `make migrate HOST_NAME=localhost NAME=vulcanize_public PORT=5432` command:

```
go get -u -d github.com/pressly/goose/cmd/goose
go get github.com/pressly/goose/cmd/goose: module github.com/pressly/goose@upgrade found (v2.6.0+incompatible), but does not contain package github.com/pressly/goose/cmd/goose
```

I restarted my computer at one point, and I have a vague recollection that the `go get -u -d github.com/pressly/goose/cmd/goose` worked previously.

**Comment by realisation** [comment]
It looks like my go installation may be out of whack. When I type `$GOPATH` in my terminal, it doesn't tell me anything.

**Comment by i-norden** [comment]
Is go modules turned on in your env? e.g. `export GO111MODULE=on`

**Comment by i-norden** [comment]
On my env I will get an error if I wipe the $GOPATH while go modules is on 

`
Ians-MacBook-Air:ipfs-blockchain-watcher iannorden$ export GOPATH=
Ians-MacBook-Air:ipfs-blockchain-watcher iannorden$ export GO111MODULE=on
Ians-MacBook-Air:ipfs-blockchain-watcher iannorden$ make migrate HOST_NAME=localhost NAME=vulcanize_public PORT=5432
go get -u -d github.com/pressly/goose/cmd/goose
go build -tags='no_mysql no_sqlite' -o /bin/goose github.com/pressly/goose/cmd/goose
go build github.com/pressly/goose/cmd/goose: open /bin/goose: operation not permitted
make: *** [/bin/goose] Error 1
`

And a different error if go modules is off 

`
Ians-MacBook-Air:ipfs-blockchain-watcher iannorden$ export GOPATH=
Ians-MacBook-Air:ipfs-blockchain-watcher iannorden$ export GO111MODULE=off
Ians-MacBook-Air:ipfs-blockchain-watcher iannorden$ make migrate HOST_NAME=localhost NAME=vulcanize_public PORT=5432
go get -u -d github.com/pressly/goose/cmd/goose
# cd /Users/iannorden/go/src/github.com/pressly/goose; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> pg_update

package github.com/pressly/goose/cmd/goose: exit status 1
make: *** [/bin/goose] Error 1
`

But no errors if I turn go modules off with a valid $GOPATH. Although, I will get an error if I run `go get -u -d github.com/pressly/goose/cmd/goose` outside of the Makefile with go modules off.

None of these errors match what you are seeing, but this could be due to other differences in the environments. The missing $GOPATH is definitely an issue although maybe not the one causing this specific error.

**Comment by realisation** [comment]
> Is go modules turned on in your env? e.g. `export GO111MODULE=on`

That solved it for me, thanks!
